version: '3.3'

services:
  kosync:
    image: koreader/kosync:latest
    container_name: kosync
    ports:
      - 8080:8080
    environment:
      - GIN_ENV=production
      - GIN_PORT=8080
    volumes:
      - ./logs/app:/app/koreader-sync-server/logs
      - ./logs/redis:/var/log/redis
      - ./data/redis:/var/lib/redis

